version: '3.9'
services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
    - "3001:3001"
    cap_add:
      - SYS_ADMIN
    environment:
    # Adjust for your environment
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=""
      - LLM_PROVIDER=ollama
      - OLLAMA_BASE_PATH=http://127.0.0.1:11434
      - OLLAMA_MODEL_PREF=llama2
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://127.0.0.1:11434
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=lancedb
      - WHISPER_PROVIDER=local
      - TTS_PROVIDER=native
      - PASSWORDMINCHAR=8
      # Add any other keys here for services or settings
      # you can find in the docker/.env.example file
    volumes:
      - anythingllm_storage:/app/server/storage
    restart: always

    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.archivebox-web-redirect.redirectscheme.scheme: https
      traefik.http.services.archivebox.loadbalancer.server.port: 8015
      # Web
      traefik.http.routers.archivebox-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.archivebox-insecure.entrypoints: web
      traefik.http.routers.archivebox-insecure.service: archivebox
      traefik.http.routers.archivebox-insecure.middlewares: archivebox-web-redirect
      # Websecure
      traefik.http.routers.archivebox.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.archivebox.entrypoints: websecure
      traefik.http.routers.archivebox.service: archivebox
      traefik.http.routers.archivebox.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.archivebox-local-insecure.rule: Host(`archivebox.${LOCAL_DOMAIN}`)
      traefik.http.routers.archivebox-local-insecure.entrypoints: web
      traefik.http.routers.archivebox-local-insecure.service: archivebox
      traefik.http.routers.archivebox-local-insecure.middlewares: archivebox-web-redirect
      # Local domain secure
      traefik.http.routers.archivebox-local.rule: Host(`archivebox.${LOCAL_DOMAIN}`)
      traefik.http.routers.archivebox-local.entrypoints: websecure
      traefik.http.routers.archivebox-local.service: archivebox
      traefik.http.routers.archivebox-local.tls: true
      runtipi.managed: true